# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia

os:
  - linux

dist: trusty

julia:
  - 1.0
  - 1.1
  - 1.2
  - 1.3
  - 1.4
  - 1.5

env:
  - JULIA_CPU_CORES=2 # travis vm only has 2 cores, but Julia reads the number of hardware cores

sudo: required

notifications:
  email:
    on_success: always
    on_failure: never

script:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - julia --color=yes -e 'using Pkg; Pkg.build(); Pkg.test("Dilemma"; coverage=true)'

after_success:
  # push coverage results to Codecov
  - julia -e 'import Pkg; cd(Pkg.dir("Dilemma")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'

jobs:
  include:
    - stage: "Documentation"
      julia: 1.4
      os: linux
      script:
        - julia --project=docs -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd())); Pkg.instantiate()'
        - julia --project=docs --color=yes docs/make.jl
      after_success: skip